<a href="https://colab.research.google.com/github/Codesorcer/VLG-Project-Generative-AI/blob/main/Generative_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from keras.models import Sequential
from sklearn.metrics import f1_score
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Generative_AI_Dataset/train.csv')
test= pd.read_csv('/content/drive/MyDrive/Generative_AI_Dataset/test.csv')
sample_sub= pd.read_csv('/content/drive/MyDrive/Generative_AI_Dataset/solution_format.csv')

In [ ]:
data

,labels,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,...,f_1190,f_1191,f_1192,f_1193,f_1194,f_1195,f_1196,f_1197,f_1198,f_1199
0,0,-2.033875,0.978446,-0.142131,-0.177117,-1.470684,1.669562,-0.196530,-0.125239,-0.452284,...,-1.111266,0.716084,0.060039,0.301279,-1.174846,-1.076498,-0.069452,-0.604012,-2.179176,0.558003
1,1,-0.348835,0.294815,-0.557577,-2.020773,-1.234715,1.633930,-1.680658,-0.358146,0.166122,...,0.735240,0.829781,1.521941,1.347946,0.754505,1.330642,-0.754453,0.582956,0.252671,1.495870
2,1,0.113248,-0.607726,-0.947791,0.830851,0.998291,0.498321,-1.493958,0.789572,-1.311018,...,0.104698,0.616189,-1.035953,2.111387,-0.984415,1.148076,-1.433554,0.243372,0.170083,1.274795
3,0,1.223321,-0.479048,-1.925789,1.680377,0.021840,-1.453307,0.605559,-0.019024,1.065448,...,0.360237,-1.957863,-0.123384,1.505329,0.660290,-1.769443,-0.547756,-0.568122,0.244645,0.982116
4,0,0.160109,0.422684,-0.308029,0.227744,0.432854,0.608348,0.193832,1.035091,-0.538868,...,0.416629,1.441766,0.212572,-0.994721,1.143999,-2.166923,-1.199248,-1.028636,0.752791,0.317169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5245,0,1.157565,-0.142219,1.043992,1.144946,1.195423,0.248978,-1.505100,-0.874137,-1.782724,...,1.195423,-0.255793,-0.154838,0.413029,-0.482939,-1.277953,-0.445082,1.195423,-0.924614,-0.432462
5246,0,1.424709,0.235910,1.356778,1.368099,-0.318862,1.039765,-0.986854,-0.330184,-1.383120,...,1.424709,-1.066107,0.881258,-0.488691,-1.281223,-1.213291,0.122692,1.175627,-1.145360,0.451026
5247,1,-0.375687,1.524455,0.012514,-0.007917,0.073809,-0.906909,-1.254247,1.606182,0.298557,...,-0.028349,-0.968204,-1.233815,1.626613,-0.191802,1.115823,0.380284,-0.293960,0.135104,1.381434
5248,1,-0.478238,1.666142,0.049609,-0.428752,-0.362771,1.798104,-0.214314,0.775400,-0.379267,...,-0.428752,-1.121552,-0.379267,-0.593705,0.049609,1.765114,0.313533,-0.329781,-1.220524,0.033114
5249,1,-0.750874,0.267008,-0.155041,-0.179867,-0.155041,-0.303999,-0.279173,1.731765,0.564925,...,-0.303999,-0.850180,0.937321,-1.594972,1.036626,1.582807,1.036626,-0.254346,0.664230,1.831071

In [27]:
# Split the data into features and labels
features = data.iloc[:, 1:]
labels = data.iloc[:, 0]

In [ ]:
features

,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,f_9,...,f_1190,f_1191,f_1192,f_1193,f_1194,f_1195,f_1196,f_1197,f_1198,f_1199
0,-2.033875,0.978446,-0.142131,-0.177117,-1.470684,1.669562,-0.196530,-0.125239,-0.452284,-0.128052,...,-1.111266,0.716084,0.060039,0.301279,-1.174846,-1.076498,-0.069452,-0.604012,-2.179176,0.558003
1,-0.348835,0.294815,-0.557577,-2.020773,-1.234715,1.633930,-1.680658,-0.358146,0.166122,-1.656990,...,0.735240,0.829781,1.521941,1.347946,0.754505,1.330642,-0.754453,0.582956,0.252671,1.495870
2,0.113248,-0.607726,-0.947791,0.830851,0.998291,0.498321,-1.493958,0.789572,-1.311018,0.848524,...,0.104698,0.616189,-1.035953,2.111387,-0.984415,1.148076,-1.433554,0.243372,0.170083,1.274795
3,1.223321,-0.479048,-1.925789,1.680377,0.021840,-1.453307,0.605559,-0.019024,1.065448,0.717341,...,0.360237,-1.957863,-0.123384,1.505329,0.660290,-1.769443,-0.547756,-0.568122,0.244645,0.982116
4,0.160109,0.422684,-0.308029,0.227744,0.432854,0.608348,0.193832,1.035091,-0.538868,0.778445,...,0.416629,1.441766,0.212572,-0.994721,1.143999,-2.166923,-1.199248,-1.028636,0.752791,0.317169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5245,1.157565,-0.142219,1.043992,1.144946,1.195423,0.248978,-1.505100,-0.874137,-1.782724,0.261597,...,1.195423,-0.255793,-0.154838,0.413029,-0.482939,-1.277953,-0.445082,1.195423,-0.924614,-0.432462
5246,1.424709,0.235910,1.356778,1.368099,-0.318862,1.039765,-0.986854,-0.330184,-1.383120,1.243559,...,1.424709,-1.066107,0.881258,-0.488691,-1.281223,-1.213291,0.122692,1.175627,-1.145360,0.451026
5247,-0.375687,1.524455,0.012514,-0.007917,0.073809,-0.906909,-1.254247,1.606182,0.298557,0.053378,...,-0.028349,-0.968204,-1.233815,1.626613,-0.191802,1.115823,0.380284,-0.293960,0.135104,1.381434
5248,-0.478238,1.666142,0.049609,-0.428752,-0.362771,1.798104,-0.214314,0.775400,-0.379267,0.725914,...,-0.428752,-1.121552,-0.379267,-0.593705,0.049609,1.765114,0.313533,-0.329781,-1.220524,0.033114
5249,-0.750874,0.267008,-0.155041,-0.179867,-0.155041,-0.303999,-0.279173,1.731765,0.564925,1.508328,...,-0.303999,-0.850180,0.937321,-1.594972,1.036626,1.582807,1.036626,-0.254346,0.664230,1.831071

In [ ]:
labels

0       0
1       1
2       1
3       0
4       0
       ..
5245    0
5246    0
5247    1
5248    1
5249    1
Name: labels, Length: 5250, dtype: int64

In [28]:
#normalizing
x = features.values
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
features_normalized = pd.DataFrame(x_scaled)

In [ ]:
features_normalized

,0,1,2,3,4,5,6,7,8,9,...,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199
0,0.207044,0.637854,0.487732,0.437158,0.301734,0.766067,0.512846,0.459553,0.538700,0.452100,...,0.331478,0.591394,0.463489,0.479639,0.337543,0.460829,0.477533,0.445382,0.255267,0.569590
1,0.451173,0.542732,0.436253,0.182685,0.334958,0.760596,0.291018,0.428104,0.620927,0.242103,...,0.569381,0.607787,0.673742,0.630661,0.595623,0.759463,0.378018,0.604149,0.566340,0.697298
2,0.518120,0.417152,0.387900,0.576284,0.649360,0.586230,0.318923,0.583077,0.424516,0.586230,...,0.488142,0.576991,0.305862,0.740816,0.363016,0.736813,0.279361,0.558727,0.555776,0.667195
3,0.678948,0.435056,0.266714,0.693541,0.511878,0.286569,0.632731,0.473895,0.740508,0.568213,...,0.521066,0.205860,0.437109,0.653369,0.583020,0.374861,0.408046,0.450183,0.565313,0.627341
4,0.524910,0.560524,0.467175,0.493039,0.569748,0.603124,0.571192,0.616229,0.527187,0.576605,...,0.528332,0.696024,0.485426,0.292642,0.647724,0.325549,0.313400,0.388585,0.630313,0.536796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5245,0.669422,0.481923,0.634707,0.619637,0.677116,0.547945,0.317258,0.358431,0.361795,0.505617,...,0.628671,0.451267,0.432585,0.495763,0.430096,0.435836,0.422963,0.686072,0.415746,0.434720
5246,0.708126,0.534536,0.673465,0.650438,0.463908,0.669366,0.394718,0.431879,0.414929,0.640487,...,0.658212,0.334435,0.581598,0.365656,0.323314,0.443858,0.505447,0.683424,0.387509,0.555023
5247,0.447283,0.713826,0.506894,0.460512,0.519195,0.370465,0.354752,0.693342,0.638537,0.477019,...,0.471001,0.348551,0.277405,0.670869,0.469040,0.732812,0.542869,0.486854,0.551301,0.681715
5248,0.432426,0.733541,0.511491,0.402425,0.457726,0.785804,0.510187,0.581164,0.548409,0.569390,...,0.419413,0.326441,0.400307,0.350504,0.501332,0.813364,0.533172,0.482063,0.377894,0.498117
5249,0.392926,0.538863,0.486132,0.436778,0.486974,0.463038,0.500493,0.710300,0.673955,0.676853,...,0.435486,0.365568,0.589661,0.206033,0.633361,0.790747,0.638220,0.492153,0.618985,0.742942

In [29]:
assert features_normalized.shape[1] == 20 * 20 * 3

In [30]:
new_values = features_normalized.values

In [31]:
features_reshaped = np.reshape(new_values, (5250, 20, 20, 3))

In [32]:
X_train, X_test, y_train, y_test = train_test_split(features_reshaped, labels, test_size=0.2, random_state=42)

In [33]:
X_train_flattened = X_train.reshape(X_train.shape[0], -1)
X_test_flattened = X_test.reshape(X_test.shape[0], -1)

In [34]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA

# Apply PCA for dimensionality reduction
pca = PCA(n_components=185)
X_train_pca = pca.fit_transform(X_train_flattened)
X_test_pca = pca.transform(X_test_flattened)
# Create an AdaBoost classifier
model = AdaBoostClassifier()

# Train the model on the PCA-transformed data
model.fit(X_train_pca, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_pca)
y_pred = np.round(y_pred).astype(int)

# Calculate F1 score
f1 = f1_score(y_test, y_pred)
print('F1 score:', f1)

F1 score: 0.708910891089109

In [35]:
# Preprocess the test data
test_features = test.iloc[:, 1:]
test_features_normalized = min_max_scaler.transform(test_features)
test_features_pca = pca.transform(test_features_normalized)

# Make predictions on the test data
test_predictions = model.predict(test_features_pca)
test_predictions = np.round(test_predictions).astype(int)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(

In [37]:
# Create a submission DataFrame
submission = pd.DataFrame({'id': test['id'], 'labels': test_predictions})

# Save the submission to a CSV file
submission.to_csv('submission.csv', index=False)

In [ ]:
# # Create the submission DataFrame
# submission = pd.DataFrame()
# submission['id'] = test['id']
# submission['labels'] = np.resize(y_pred, len(test))

# # Save the submission to a CSV file
# submission.to_csv('submission5.csv', index=False)

In [ ]:
# # Create the CNN model
# model = Sequential()
# model.add(Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=(20, 20, 3)))
# model.add(MaxPooling2D((2, 2), strides=2))
# model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
# model.add(MaxPooling2D((2, 2), strides=2))
# model.add(Flatten())
# model.add(Dense(1024, activation='relu'))
# model.add(Dense(1, activation='sigmoid'))

In [ ]:
# # Compile the model
# model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# y_train = np.array(y_train)
# # Train the model
# model.fit(X_train, y_train, epochs=10, )

# # Evaluate the model
# score = model.evaluate(X_train, y_train, verbose=0)
# print('Accuracy:', score[1])

# # Evaluate the model on the test set
# y_pred = model.predict(X_test)
# y_pred = np.round(y_pred).astype(int)

# # Save the model
# model.save('model.h5')

Epoch 1/10
132/132 [==============================] - 8s 41ms/step - loss: 0.4904 - accuracy: 0.7657
Epoch 2/10
132/132 [==============================] - 9s 67ms/step - loss: 0.3586 - accuracy: 0.8336
Epoch 3/10
132/132 [==============================] - 6s 42ms/step - loss: 0.3133 - accuracy: 0.8552
Epoch 4/10
132/132 [==============================] - 7s 54ms/step - loss: 0.2670 - accuracy: 0.8807
Epoch 5/10
132/132 [==============================] - 6s 46ms/step - loss: 0.2152 - accuracy: 0.9064
Epoch 6/10
132/132 [==============================] - 6s 48ms/step - loss: 0.1690 - accuracy: 0.9374
Epoch 7/10
132/132 [==============================] - 7s 53ms/step - loss: 0.1233 - accuracy: 0.9550
Epoch 8/10
132/132 [==============================] - 6s 42ms/step - loss: 0.0941 - accuracy: 0.9686
Epoch 9/10
132/132 [==============================] - 8s 58ms/step - loss: 0.0566 - accuracy: 0.9852
Epoch 10/10
132/132 [==============================] - 6s 42ms/step - loss: 0.0338 - accuracy: 0.9921
Accuracy: 0.9997618794441223
33/33 [==============================] - 0s 10ms/step

In [ ]:
# # Create the submission DataFrame
# submission = pd.DataFrame()
# submission['id'] = test['id']
# submission['labels'] = np.resize(y_pred, len(test))

# # Save the submission to a CSV file
# submission.to_csv('submission.csv', index=False)

In [ ]:
# model = tf.keras.Sequential([
#     Conv2D(32, (3, 3), activation='relu', input_shape=(20, 20, 3)),
#     MaxPooling2D((2, 2)),
#     Conv2D(64, (3, 3), activation='relu'),
#     MaxPooling2D((2, 2)),
#     Conv2D(64, (3, 3), activation='relu'),
#     Flatten(),
#     Dense(64, activation='relu'),
#     Dense(2, activation='softmax')
# ])

In [ ]:
# model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
# history = model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
132/132 [==============================] - 6s 25ms/step - loss: 0.5474 - accuracy: 0.7340 - val_loss: 0.4637 - val_accuracy: 0.8010
Epoch 2/10
132/132 [==============================] - 2s 18ms/step - loss: 0.4089 - accuracy: 0.8017 - val_loss: 0.3825 - val_accuracy: 0.8181
Epoch 3/10
132/132 [==============================] - 2s 19ms/step - loss: 0.3505 - accuracy: 0.8386 - val_loss: 0.3646 - val_accuracy: 0.8476
Epoch 4/10
132/132 [==============================] - 2s 19ms/step - loss: 0.3005 - accuracy: 0.8598 - val_loss: 0.3669 - val_accuracy: 0.8352
Epoch 5/10
132/132 [==============================] - 3s 26ms/step - loss: 0.2557 - accuracy: 0.8840 - val_loss: 0.3907 - val_accuracy: 0.7943
Epoch 6/10
132/132 [==============================] - 3s 24ms/step - loss: 0.2195 - accuracy: 0.9048 - val_loss: 0.4455 - val_accuracy: 0.8410
Epoch 7/10
132/132 [==============================] - 2s 19ms/step - loss: 0.1735 - accuracy: 0.9255 - val_loss: 0.4425 - val_accuracy: 0.8048
Epoch 8/10
132/132 [==============================] - 2s 17ms/step - loss: 0.1257 - accuracy: 0.9531 - val_loss: 0.5382 - val_accuracy: 0.7810
Epoch 9/10
132/132 [==============================] - 2s 19ms/step - loss: 0.0994 - accuracy: 0.9626 - val_loss: 0.6409 - val_accuracy: 0.7905
Epoch 10/10
132/132 [==============================] - 3s 22ms/step - loss: 0.0387 - accuracy: 0.9917 - val_loss: 0.7148 - val_accuracy: 0.7800

In [ ]:
# data_1 = pd.DataFrame(features_normalized, columns=data.columns[1:])
# data_1.to_csv('normalized_train.csv', index=False)

In [ ]:
# # Load the normalized dataset from the CSV file
# data = pd.read_csv('normalized_train.csv')

# # Split the dataset into training and testing sets
# train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

# # Save the training and testing sets to separate CSV files
# train_data.to_csv('train_data.csv', index=False)
# test_data.to_csv('test_data.csv', index=False)

In [ ]:
# #split new data into features and labels
# X_train = train_data.iloc[:, 1:].values
# y_train = train_data.iloc[:, 0].values
# X_test = test_data.iloc[:, 1:].values
# y_test = test_data.iloc[:, 0].values